### ISSUE TITLE
Equally disperse secondary menu items and allow submenus

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_APPLEGATE#12]
For the green gradient menu that sits above the footer, we need to allow for hover activated dropdown submenus and also evenly disperse the top level items across the page width.

**Comment by joelworsham** [comment]
This wouldn't match the mocks. Did we decide to do something different?

Submenus beneath would be tough with the footer, just because they're so close to the bottom of the page. Maybe they should pop-up above?

**Comment by brashrebel** [comment]
You could try that. I'm ok with it and I think we can make a strong case that it would be a better UX. Good idea. Pop them up.

**Comment by brashrebel** [comment]
The green gradient menu items are not equally dispersed. They need to all take up the same percentage of the menu width.

Also, can we have some sample links inserted as submenu items for these so we can experience and test the hover/popup idea?

**Comment by joelworsham** [comment]
Submenus exist, just none were set. But i now realize the mobile experience is bugged

**Comment by brashrebel** [comment]
Still need to equally disperse these.
