### ISSUE TITLE
Products thingy on home page

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_APPLEGATE#13]
Client has determined that the massive green bar below the 4 personas does not translate as a "button" for most viewers so it needs to be reimagined. We debated a bit on the actual solution and are going to go with _something_ below those personas which directs the viewer to all products.

I'm thinking something very similar to what you originally had on the top of your first concept. Only differences would be removing the "read more about us" text and possibly add some kind of text blurb above the button. Let's see how that works out.

**Comment by joelworsham** [comment]
I don't understand what it is you've decided would be best. You want me to create another "section" below _identical_ to my original concept but without the "read more about us" text? But basically the same look? (green textured back, copy above)

**Comment by brashrebel** [comment]
Yep, that's pretty much the idea I guess. Replace the giant button that is there now.
