### ISSUE TITLE
Adding / Editing products pages...

### ISSUE THREAD

**Issue by pvankirk** [realbig/TH_APPLEGATE#19]
First off, this is my first ticket, so I don't know if you would prefer I gang multiple issues or if you would rather they be provided one per ticket so you can more easily track progress and comments and tick them off as they are addressed. I will assume the later as that seems to make more sense. Let me know if otherwise.

Issue: Not sure how I can add products or product categories. I see buckets for Contractors, Builders, Homeowners and Code Officials, but nothing for products. I also don't see a template for products. I am trying to stick with a single template layout for the site (buckets differentiated by color) to keep things simple. I would like the green theme used in the products icon to carry through for the page template. This should also be available for other pages that are not children of the buckets.

**Comment by BigActual** [comment]
One per is perfect Paul. Joel/Kyle is this to become a CPT with dashboard access and it's own interface area?

**Comment by brashrebel** [comment]
@pvankirk thanks for describing this and we'll address in the next phase with more clear instructions.

**Comment by joelworsham** [comment]
Yes, this is already in place.

To access products in the admin area of the site, hover over "Products" in the left-side menu, when in the admin area.

From there you can find a list of all your products as well as the Categories and Buckets.

**Comment by pvankirk** [comment]
I have reviewed and the functionality of this page is different from the others. It should look and function as any of the other "buckets". Under the color bar should be secondary navigation that can link to product groups (Cellulose, Cotton) or other information relating to products. Ultimately, each product will have its own page. Should I just create a Products "bucket"?

**Comment by joelworsham** [comment]
I will need to add a special page template for that first.
