### ISSUE TITLE
Not sure how to define a page for menu items...

### ISSUE THREAD

**Issue by pvankirk** [realbig/TH_APPLEGATE#20]
Issue: Not sure how to create a page for a menu item like 
Paper Drive" and link it back to that item.

**Comment by BigActual** [comment]
Acknowledged. Permission issue, menu's not available to client. Please modify

**Comment by joelworsham** [comment]
Permissions elevated to Administrator.

**Comment by BigActual** [comment]
Thanks Joel,
@pvankirk please hold off on modifying menus until Kyle has walked through this with you on the next round. It's not a difficult area to deal with, but a walk through will make this easy.
