### ISSUE TITLE
Not sure how to manage list items in footer...

### ISSUE THREAD

**Issue by pvankirk** [realbig/TH_APPLEGATE#21]
Issue: I'm not sure where/how to manage the items in the footer of the page. My original understanding was those items would build dynamically based upon pages being added to the site (e.g. add a calculator page to "Contractors" page, a "Calculators" item would show up in the list at the bottom of the page, linked back to the appropriate page.

**Comment by BigActual** [comment]
Acknowledged. Reviewing with Joel and Kyle.

**Comment by joelworsham** [comment]
It is a manually created menu, managed in the WordPress Menus administration screen.

We can talk about the possibility of automatically populated menus, but for now, it's manual

**Comment by BigActual** [comment]
Paul, when the site goes live, do you want this to be manual or automatic?

**Comment by pvankirk** [comment]
My preference would be automatic as I will be heavily focused on adding content, but it can be made a low priority item. Lets manage all other issues first, but not delay launch due solely to this. Thanks.

**Comment by BigActual** [comment]
Excellent. @joelworsham Please add this to the check list for final launch.

**Comment by joelworsham** [comment]
The 5 footer menu columns now come from a new Applegate Settings page (found in the admin screen, in the `Settings` page menu).

You are provided 5 menu item top level pages. Each one of these represents the top-most level page to use for the menu column. Each page will then list its children as menu items accordingly.
