### ISSUE TITLE
How do I manage items in the cascading menus?

### ISSUE THREAD

**Issue by pvankirk** [realbig/TH_APPLEGATE#23]
Issue: Not sure how or where I would add/edit/remove menu items to the cascading menus.

**Comment by BigActual** [comment]
This is partially a permission issue and partially a training issue Paul. Menus are only manageable through the menu section on the control panel. This is turned on, and we train the client on how to manage menus, when the project is complete. For now, would you be so kind as to keep it simple for us by requesting a menu edit/add/deletion within GitHub and we'll take care of those changes. Many thanks for that. 
Kyle will certainly show you how to manage menu items very soon. It's not hard, but we've had clients in the past who assumed they knew how to manage menus make development difficult by changing which menus appear in the wrong places. This is overcome with a walk through. I appreciate your patience here.

**Comment by pvankirk** [comment]
That isn't a problem. I welcome any training you believe will help us more effectively manage the site. I won't tinker until we talk. Paul
