### ISSUE TITLE
How do I manage the blog that is linked to through the bible verse?

### ISSUE THREAD

**Issue by pvankirk** [realbig/TH_APPLEGATE#24]
Issue: I see the link is active, but I'm not sure how/where I can modify the blog page that is linked back to the bible verse.

**Comment by BigActual** [comment]
Playing catch-up. What's the desired outcome @pvankirk ? Is this to be a situation where every time the home page loads another quote is posted with no other interaction, or is the quote to be an item with a hotlink to another page of all quotes? I'm using the term quote lightly as in the sense that these are quotes from the Good Book.

**Comment by pvankirk** [comment]
The bible verse will be static. If you recall from our original conversation, the goal is to move non-business content from the business site to a blog page where Terry could post thoughts, comments and articles, and engage in dialog with visitors who opted to reply to his postings. You had provided me with a couple of other companies that had taken a similar approach at the time. He would need to maintain administrative control over all postings (no comments are visible without his approval). Visually, this blog would be different from the business site.

**Comment by BigActual** [comment]
Thanks for the refresh. Yes, I recall that. Ok, so you need a log on for that blog for you, for Terry, or for both of you? You indicated earlier that it would just be you. No change there?

**Comment by pvankirk** [comment]
Should be both.Terry will neither need, nor want, access to revised design. He will want administrative permissions for authoring and managing comments. As with any Applegate related site, I will want the full monte. I know not to push the big red button...

**Comment by BigActual** [comment]
Hi, my name is Paul, and I work in a button factory... I digress.
@brashrebel would you please make sure to discuss this with Paul. He'll need to understand how to switch between sites as that blog is a separate domain, site, etc. Have we set up some type of a side project for this? Just curious. I'd hate to leave Mr. Applegate with a set of tools and a lack of understanding on how to effectively use them. Do we need to style the site? what's the best way to address that, etc. Thanks guys.

**Comment by brashrebel** [comment]
@pvankirk I believe you're referring to the applegateblog.com site which I haven't set you up as a user for yet. It will be addressed in the next phase and we'll provide instructions.

**Comment by pvankirk** [comment]
OK, just let me know. We will have live links from the insulation website and I want to make sure they go someplace done.

**Comment by joelworsham** [comment]
I think the initial question here is how to access where the Bible verse is linked.

You may do so from the Widgets page in the Widgetized Area - "Header Bible Verse".

Here's a link: http://insulation.applegateblog.com/wp-admin/customize.php?url=http%3A%2F%2Finsulation.applegateblog.com%2F&autofocus%5Bpanel%5D=widgets

**Comment by joelworsham** [comment]
Unless I'm misunderstanding?

**Comment by pvankirk** [comment]
This page...

http://www.applegateblog.com/wp-signup.php?new=applegateblog.com

**Comment by brashrebel** [comment]
@joelworsham the question is about the destination. We need to do some simple work on applegateblog.com to stop it from redirecting to the signup page and to get Paul set up on it so he can manage the content.

**Comment by pvankirk** [comment]
Yes, and thank you.

**Comment by joelworsham** [comment]
It is working now
