### ISSUE TITLE
How do I manage the social links?

### ISSUE THREAD

**Issue by pvankirk** [realbig/TH_APPLEGATE#25]
Issue: Not sue where I can manage the social links on the page. In the future we may want to add more social links.

**Comment by BigActual** [comment]
@joelworsham What's the best method for providing client management here? Widget or some type of dashboard interface???

**Comment by pvankirk** [comment]
I'm OK if this isn't managed by me, I just didn't see an interface where I could add the correct link for each social icon.

**Comment by joelworsham** [comment]
Right, this has not yet been implemented. It will be though soon.
