### ISSUE TITLE
How do I manage the icons for the buckets on the home page?

### ISSUE THREAD

**Issue by pvankirk** [realbig/TH_APPLEGATE#26]
Issue: I can't locate a place to manage the icons for the buckets for the icons. Are those coded, or will I have editorial control?

**Comment by joelworsham** [comment]
As of now they are coded in. It would be easiest to, rather than providing control, collaboratively decide on which ones to use. I'm assuming they won't be changing after initial implementation.

Here are the available icons: http://fortawesome.github.io/Font-Awesome/icons/

**Comment by pvankirk** [comment]
Coded is fine. We may (hopefully) add more in the future, but those can be coded in at that time. Changes will not be a regular occurrence.
