### ISSUE TITLE
Responsive design for mobile needs work...

### ISSUE THREAD

**Issue by pvankirk** [realbig/TH_APPLEGATE#27]
Issue: Navigation in mobile layout is awkward.

We need to reduce the size of elements much like was done in my original layout (attached) so more of the links more above the fold (ignore the tabs look). We also need to eliminate the duplication of navigation buckets at the bottom of the page.

The menu items reversed in the top need to be dropped. Move social to the bottom of the page. The order for the bucket should be Contractors, Officials, Homeowners, Architects, Products. Ultimately, we will be promoting a section for contractors where they can find videos and content that will help them resolve issues in the field. This will also be the first line of defense for our customer service and sales reps so they can send contractors to a visual walk-through solution.

to help save space, please also remove the "Welcome" statement.

The search box should move outside of the black header area.

![landing page mobile layout-01](https://cloud.githubusercontent.com/assets/13487679/8882269/a3e7d6da-3213-11e5-8b13-6573e8296bc5.jpg)

**Comment by BigActual** [comment]
Acknowledged. @joelworsham please add these changes to the next round. Thanks in advance.

**Comment by pvankirk** [comment]
This is significantly better but still needs a little polish. I couldn't work out how to reopen this issue, so I will just add my comments:

1) The Welcome statement needs to go.
2) The space between the bible verse and the next block of copy, and between the "We've made it easier..." copy and the bucket buttons needs to be halved.
3) The text label inside the buckets needs to be larger. Can flow to two lines if required. Probably about 3 point sizes larger.
4) We lost the search box. It should only be moved to below the black header space.
5) When I go to the "Contractor & Professionals" bucket or the "Architects & Specifiers" bucket, the text in the red or blue bar bar flows into two lines. It should scale down to remain on a single line.

Thanks!
