### ISSUE TITLE
Code to embed YouTube video isn't working...

### ISSUE THREAD

**Issue by pvankirk** [realbig/TH_APPLEGATE#28]
Issue: I pulled the code from a video on our YouTube channel however, when I try to update the page after adding the code the video disappears. I have also tried adding it as a URL through the media library which was also unsuccessful. I was able to cut and paste a url into the page which added the video, however I have no control over the size, and it auto-plays the next video (not mine) when finished.

**Comment by BigActual** [comment]
Right, adding a video from YouTube is a process that's been mulled over within WordPress core and enhanced as time has progressed using oEmbed. There's' information at the bottom of this post about controlling video size and display of other content, but Here's an excerpt from the WordPress communities codex about how to place video(Looks like you're on the right track):

Usage
To embed a video or another object into a post or page, place its URL into the content area. Make sure the URL is on its own line and not hyperlinked (clickable when viewing the post).

For example:

Check out this cool video:
http://www.youtube.com/watch?v=dQw4w9WgXcQ
That was a cool video.

WordPress will automatically turn the URL into a YouTube embed and provide a live preview in the visual editor.

Another option is to wrap the URL in the [embed] Shortcode.

[embed width="123" height="456"]http://www.youtube.com/watch?v=dQw4w9WgXcQ[/embed]
If WordPress fails to embed the URL, the post will contain a hyperlink to the URL.

You can read more about it here: https://codex.wordpress.org/Embeds

FOR FINER CONTROL...
Also, Google has placed the onus for managing whether another video is presented to the site's End Users in the hands of the person adding the video. When you select a video for sharing on YouTube, there are buried options in their interface, under the video. See the attached screen shot:
![image](https://cloud.githubusercontent.com/assets/8271108/8911249/3aac412c-3459-11e5-808e-2af8b6eb03ba.png)

**Comment by BigActual** [comment]
If this answers your question, please feel free to close the issue with the button below. If you have additional questions, post them here and I or one of the team would be happy to help.

**Comment by pvankirk** [comment]
I will try it out and respond shortly, or close if resolved. Thanks.

**Comment by BigActual** [comment]
No problem.

**Comment by pvankirk** [comment]
Steve, when I pull the embed code, it uses iframe which doesn't play nice. If I change the code to embed it works, but I lose the ability to manage the controls. I can size it, but I can't keep it from recommending a next video (which is usually a competitor's...) Would it help if I were to post specific syntax?

**Comment by BigActual** [comment]
@brashrebel , please advise.

**Comment by brashrebel** [comment]
In short, embedding YouTube videos should be done via the URL method. This will make the video responsive whereas the iframe code would give it fixed dimensions and provide a terrible experience for smaller screens. If we need to specify the dimensions to be different then what they default to I can provide a solution for that. Also, we will look into implementing something that overrides the default recommended videos behavior from YouTube as well.

**Comment by pvankirk** [comment]
I guess the basic parameters that I would want are as follows:
- Video appears no wider than 1-column in desktop view.
- Video can be screen width in mobile view.
- Video does not auto-play next video, or recommend a next video.
- Video can be expanded to full-screen by user.

Any other recommendations? Thoughts on auto-play vs manual activation? I lean toward manual activation, especially since some pages could have multiple videos posted to them.

If I could get a block of code that I could wrap around a URL, it would be very helpful for me when filling pages with content.

Thanks!

**Comment by brashrebel** [comment]
We will look into the best solution for what you've described. I want to make it as easy for you as possible while still empowering you to create content the way you want it.

And I would recommend against auto-playing a video.

**Comment by BigActual** [comment]
I'll second that recommendation. Based on what we've learned, people generally are there to watch the video and plan on hitting play.  having it start at their behest gives the user time to rearrange their desktop, move other items out of the way, turn down their volume, etc. Autoplay can come across as spammy. It can also put a user in an uncomfortable position if they're in the office and their volume is turned up or if they're not actually ready to watch the video.The optimum solution we've found is video available, with a transcript on the page for those who don't want to or can't watch the video.

**Comment by joelworsham** [comment]
@pvankirk Could I get some clarification on what you mean by "1 column"?

**Comment by pvankirk** [comment]
Our standard page uses two columns of body copy below the large photo. I would like to have videos be as wide as a single column of body copy and to change size at the same rate the column of text would when a window size is adjusted (it is responsive like other page elements). Does that make sense?

**Comment by joelworsham** [comment]
Yes! Thanks for the clarification.

**Comment by pvankirk** [comment]
Nice!
