### ISSUE TITLE
Footer menu missing

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_APPLEGATE#30]
Menu exists and so does footer menu location and the menu is assigned to that location but nothing shows up.

**Comment by joelworsham** [comment]
This was changed recently, per the client's request. You can read more about it in #21.

**Comment by joelworsham** [comment]
I can remove the location from the theme to clear up confusion. I meant to.

**Comment by pvankirk** [comment]
Footer is still missing. Can we please reopen?

**Comment by joelworsham** [comment]
As I mentioned in #21, you need to go to http://insulation.applegateblog.com/wp-admin/options-general.php?page=applegate-settings and setup the footer columns. If you need assistance, I can provide more specific instructions.

**Comment by pvankirk** [comment]
Sorry, looks self-explanatory to me. Is there a way to add the image back into the background behind the columns?

**Comment by brashrebel** [comment]
@pvankirk are you referring to the picture of dirt with columns in it? I kind of remember that. My concerns with adding that are as follows:
- An image background introduces an inconsistency with the site's aesthetic as nothing else is employing graphics to style static layouts.
- The columns in the image don't and can't possibly consistently align with the footer menu columns. At some screen widths it will look ok but at most, the columns will intersect with the listed text which to me will look wrong.

These are subjective issues so really, if you decide the image needs to be there, we'll add it. My opinion is that it does not add value to the design and could possibly detract from it.
