### ISSUE TITLE
Order field is not setting order in link list...

### ISSUE THREAD

**Issue by pvankirk** [realbig/TH_APPLEGATE#39]
If I am understanding how this field works correctly, it should allow me to force a non-alphabetical order of the menu items. Right now, it doesn't appear to do anything. Can you please confirm functionality? If this does not accomplish this, how can I control the list order?

Example: "Calculators" under "building Professionals" displays first in the list, however I would like it last.

**Comment by joelworsham** [comment]
Sure thing. I can set this up so that "Menu Order" does indeed control the order of the "Bucket Menus".
