### ISSUE TITLE
Bucket Nav bar (color stripe) disappears when navigating down two levels

### ISSUE THREAD

**Issue by pvankirk** [realbig/TH_APPLEGATE#40]
If I go to Architects-->Benefits-->Savings, the blue bar doesn't show.

**Comment by joelworsham** [comment]
The "Savings" page needs to have a bucket selected for a bucket bar to show.

Select it from here:
https://i.imgur.com/hRNITMv.png

**Comment by pvankirk** [comment]
Thanks, Resolved.

**Comment by joelworsham** [comment]
No problem!
