### ISSUE TITLE
"Buckets" aren't showing correctly on home page/Dupe of Products...

### ISSUE THREAD

**Issue by pvankirk** [realbig/TH_APPLEGATE#41]
There are two "Products" buckets on the home page which is essentially pushing remaining buckets is list, so colors are off as well. Both links to Products bucket result in a fatal error.

**Comment by joelworsham** [comment]
This was an old issue that doesn't seem to be showing up for me anymore. Is this still happening for you?

**Comment by pvankirk** [comment]
It has cleared but, the link goes to an unknown location. I spoke with Kyle about the Products page last week and we discussed a couple of different approaches on how to handle the need for unique content on the products pages for each bucket. Did he speak with you about this and make a decision on what approach to take?

**Comment by joelworsham** [comment]
I think this has to do with #46? I'll let the conversation continue there.
