### ISSUE TITLE
Size of "Bucket" graphics vary based on length of title

### ISSUE THREAD

**Issue by pvankirk** [realbig/TH_APPLEGATE#42]
When the title fits on a single line, the graphic is shorter. Can we just add an extra return to make up the difference?

**Comment by joelworsham** [comment]
Where are you referring to?

**Comment by pvankirk** [comment]
Issue is no longer appearing. Maybe I saw it while your work was in progress?

**Comment by joelworsham** [comment]
That is a possibility. Glad to hear it's working!
