### ISSUE TITLE
Products and associate pages/content not functioning correctly...

### ISSUE THREAD

**Issue by pvankirk** [realbig/TH_APPLEGATE#47]
I have created a page called "Products". When I click any link, the page is the basic template, but my test copy doesn't appear. The green bar doesn't appear either. This is true even when attempting to view the page directly from the page editor.

When I create a child of Products, it won't show any content unless I have created a product through the products cart tool and then it loads the content from the product created rather than the page. It shows as a blog entry.

**Comment by joelworsham** [comment]
Apologies. Was a conflict with the products plugin

**Comment by joelworsham** [comment]
Children pages still not functioning. Will be working momentarily
