### ISSUE TITLE
Getting time-out errror-can't load content

### ISSUE THREAD

**Issue by pvankirk** [realbig/TH_APPLEGATE#52]
I'm getting the follwoing error that is causing issues with adding header images to pages. They won't upload.

"Stream API Error. SSL peer certificate or SSH remote key was not OK."

Any thoughts? I am working remotely presently...

**Comment by pvankirk** [comment]
![web error](https://cloud.githubusercontent.com/assets/13487679/10796940/b4d46f22-7d76-11e5-9b53-e5bb1f750744.jpg)

**Comment by brashrebel** [comment]
@pvankirk this is on our list to address ASAP. Should be dealt with this week.
