### ISSUE TITLE
Fix icon overlap when buckets stack on home page

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_APPLEGATE#7]
Currently when viewing the home page on a narrow screen, all stack but hovering on one results in the next below's icon being half covered. Doesn't look right to me.

**Comment by joelworsham** [comment]
There is no hover on mobile (99.9999% of screens that small :P). So I think the issue is moot

**Comment by joelworsham** [comment]
Although, the change _does_ happen at medium...

**Comment by joelworsham** [comment]
Alright alright. I fixed it anyways. I also changed the breakpoint from medium to small.
